In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [2]:
class Net(nn.Module):
    def __init__(self): #定义神经网络结构, 输入数据 1x32x32
        super(Net, self).__init__()
        # 第一层（卷积层）
        self.conv1 = nn.Conv2d(1,6,3) #输入频道1， 输出频道6， 卷积3x3
        # 第二层（卷积层）
        self.conv2 = nn.Conv2d(6,16,3) #输入频道6， 输出频道16， 卷积3x3
        # 第三层（全连接层）
        self.fc1 = nn.Linear(16*28*28, 512) #输入维度16x28x28=12544，输出维度 512
        # 第四层（全连接层）
        self.fc2 = nn.Linear(512, 64) #输入维度512， 输出维度64
        # 第五层（全连接层）
        self.fc3 = nn.Linear(64, 2) #输入维度64， 输出维度2
    
    def forward(self, x): #定义数据流向
        x = self.conv1(x)
        x = F.relu(x)
        
        x = self.conv2(x)
        x = F.relu(x)
        
        x = x.view(-1, 16*28*28)
        x = self.fc1(x)
        x = F.relu(x)
        
        x = self.fc2(x)
        x = F.relu(x)
        
        x = self.fc3(x)
        
        return x
        

In [3]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)


In [4]:
#生成随机输入
input_data = torch.randn(1,1,32,32) 
print(input_data)
print(input_data.size())

tensor([[[[-0.5518,  0.0649,  0.9500,  ...,  0.2207, -1.1846, -0.5081],
          [-0.5137,  0.6061,  0.2845,  ..., -0.6264, -0.8313,  0.4624],
          [ 0.3367, -1.1461,  0.8586,  ..., -1.4342,  0.3141,  1.2599],
          ...,
          [-0.4495,  1.7554, -1.1736,  ..., -1.5489,  1.8449,  1.5590],
          [-0.8913,  0.5652,  1.0342,  ..., -0.4757,  1.1992,  0.8304],
          [ 0.1675, -1.3038,  2.6100,  ..., -1.1493,  0.3754, -0.3571]]]])
torch.Size([1, 1, 32, 32])


In [5]:
# 运行神经网络
out = net(input_data)
print(out)
print(out.size())

tensor([[-0.0965,  0.0616]], grad_fn=<ThAddmmBackward>)
torch.Size([1, 2])


In [6]:
# 随机生成真实值
target = torch.randn(2)
target = target.view(1,-1)
print(target)

tensor([[-1.1073,  0.6537]])


In [7]:
criterion = nn.L1Loss() # 定义损失函数
loss = criterion(out, target) # 计算损失
print(loss)

tensor(0.8014, grad_fn=<L1LossBackward>)


In [8]:
# 反向传递
net.zero_grad() #清零梯度
loss.backward() #自动计算梯度、反向传递


In [9]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.step()

In [10]:
out = net(input_data)
print(out)
print(out.size())

tensor([[-0.1450,  0.1121]], grad_fn=<ThAddmmBackward>)
torch.Size([1, 2])
